FROM node:25.6.0-slim

RUN apt update \
  && apt install -y --no-install-recommends procps curl ffmpeg \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

RUN mkdir -p /home/node/app/node_modules \
  && chown node:node /home/node/app/node_modules

USER node

CMD [ "tail", "-f", "/dev/null" ]
