FROM node:25.6.0-slim

RUN apt update \
  && apt install -y --no-install-recommends ffmpeg procps curl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

COPY package.json ./
RUN npm install

USER node

CMD ["npm", "run", "start:worker"]
